config/routes.rb
Traveler::Application.routes.draw do

  match "trip_segments/order_by_distance/:destination", :to => "trip_segments#order_by_distance", :as => :order_by_destination_distance
  match "trip_segments/destination/:destination" => "trip_segments#limit_by_destination", :as => :destination, :via => :get       # , :contraints => { :destination => /^[a-zA-Z0-9]*$/}
  match "trip_segments/index_by_trip/:trip_id" => "trip_segments#index_by_trip", :as => :all_segments_for_trip, :via => :get
  match "trip_segments/search" => "trip_segments#search", :via => :get

  resources :trip_segments do
    get :index_ordered_by_origin, :as => :order_by_origin, :on => :collection
  end

  resources :trips do
    get :index_all, :on => :collection
  end

  match "locales/:origin/:destination" => "locales#show_segment_locales", :as => :locales_seg ,:via => :get
  match "locales/trip/:trip_id" => "locales#show_trip_locales", :as => :all_locales_trip ,:via => :get

  resources :locales, :only => "show"       # <<< limit it to show for now.

  root :to => "trips#index"

end

app/models/locale.rb
class Locale < ActiveRecord::Base

  geocoded_by :name, :latitude  => :lat, :longitude => :lng
  before_save :geocode, :if => :in_dev?

  validates :name, :uniqueness => true

  scope :location, lambda { |loc| where("name = ?", loc)}

  def to_s
    name
  end

  def in_dev?
    false
    # Rails.env.development? # <<< lame, but could not figure out how to tell gem not to call google in test.
  end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :name, :presence => true    # Rails3 slightly different validation syntax

  has_many :trip_segments

  scope :hong_kong, where("trips.name LIKE ?", "%Hong Kong%")

  # trip name and segment name, ordered by trip name, of 5 trips, with segments joined, where trip < today
  scope :super_chained_join_scope, joins(:trip_segments).select("trips.name tname, trip_segments.name sname").order("trips.name DESC").where("trip_segments.start_date < ?", Time.now + 1.day).hong_kong.limit(5)

  scope :super_chained_include_scope, includes(:trip_segments).select("trips.name tname, trip_segments.name sname").order("trips.name DESC").where("trip_segments.start_date < ?", Time.now + 1.day).hong_kong.limit(5)

  def total_miles
    trip_segments.sum("distance_in_miles")
  end

  def longest_segment_of_trip
    trip_segments.order("distance_in_miles").last  # <<< does limit 1 under the covers
  end
end



# class Book < ActiveRecord::Base
#     validates :title, :presence => true # Always run
#     validates :proofread, :inclusion => {  :in => [true, false] }, :on => :publish # Skipped on create or update
#
#     def publish!
#       # Note the ":publish" argument on #valid? -- we're telling the model to run validations for the ":publish" context
#       valid?(:publish) && toggle(:published) && save!
#     end
#   end

app/models/trip_segment.rb
class TripSegment < ActiveRecord::Base

  belongs_to :trip

  belongs_to :locale_origin, :class_name => "Locale"
  belongs_to :locale_destination, :class_name => "Locale"

  validates :locale_origin_id, :locale_destination_id, :distance_in_miles, :presence => true    # Rails3 slightly different validation syntax
  validate :validation_origin_destination
  validates :distance_in_miles, :numericality => {:greater_than => 100}
  validates_datetime :start_date, :allow_nil => true
  validates_datetime :end_date, :allow_nil => true

  # before_save :generate_trip_segment_name, :unless => :name?

  scope :destination, lambda { |dest| where("locales.name = ?", dest).joins(:locale_destination)}     # Rails3 scope
  scope :order_by_miles_to_destination, lambda { |dest| destination(dest).order("trip_segments.distance_in_miles DESC") }    # Rails3 scoper....reusing another scope in sort of a contrived way.

  def validation_origin_destination
    errors.add(:base,"Origin and Destination must be different") if locale_origin_id == locale_destination_id    # Rails3 slightly different?
  end

  #  Could be association is not created when this is called, causing issues.
  # def generate_trip_segment_name
  #   self.name = "#{locale_origin.name} - #{locale_destination.name}"
  # end

  def self.longest_segment
    order("distance_in_miles").last   # <<< could'vd done a scope. now that I think about it.
  end

  # class << self
  #   def search(q)
  #     query = "%#{q}%"
  #     # where("trip_segments.origin LIKE ? OR trip_segments.destination LIKE ?", query,query)
  #
  #     joins(:locale_origin,:locale_destination).where("name like ?", loc)}
  #
  #   end
  #
  #   # dynamic scope construction; not sure it is R3s-specific
  #
  #   # NOTE: one can NOT chain where clauses with "or"; default is "AND"; only a gem will help.
  #   # def search(locale)
  #   #   [:origin, :destination].inject(scoped) do |combined_scope, attr|
  #   #     combined_scope.where("trip_segments.#{attr} LIKE ?", "%#{locale}%")
  #   #   end
  #   # end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController

  def show
    @locale = Locale.find(params[:id])
  end

  def show_segment_locales
    @locales = [Locale.location(params[:origin]).first,Locale.location(params[:destination]).first]
    render "show_locales"
  end

  def show_trip_locales
    @locales = []
    trip = Trip.find(params[:trip_id])
    trip.trip_segments.each do |seg|
      @locales << seg.locale_origin
      @locales << seg.locale_destination
    end
    render "show_locales"
  end
end

app/controllers/trip_segments_controller.rb
class TripSegmentsController < ApplicationController

  def index
  end

  def index_by_trip
    @trip = Trip.find(params[:trip_id])   # <<<< "find" the call is made immediately; not relation lazy loading.
  end

  def index_ordered_by_origin
    @trip_segments = TripSegment.order("origin")  # Rails3 new method for ordering

    # Add another query here it see how a returned Arel "relation" works.
    # Should not produce a query in the log because it is never really used.
    # In log: Trip Load (0.2ms)  SELECT "trips".* FROM "trips" WHERE (name LIKE '%Hong Kong%')
    # when explicitly attempted to be displayed. No logged query otherwise.

    @hong_kong_trips_lazy = Trip.hong_kong   # Lazy
    @hong_kong_trips_now = Trip.hong_kong.all  # Now - query executes immmediately.

  end

  def show
    # @trip_segment = TripSegment.where(:id => params[:id])     <== returns an array, not a single occurence. not correct.
    @trip_segment = TripSegment.find(params[:id])
  end

  def edit
    @trip_segment = TripSegment.find(params[:id])
  end

  def new
  end

  def update
    @trip_segment = TripSegment.find(params[:id])
    if @trip_segment.update_attributes(params[:trip_segment])
      redirect_to trip_segments_path
    else
      render :edit
    end

  end

  def create
    org_location = Locale.location(params[:origin]).first
    org_location = Locale.create!(:name => params[:origin]) if org_location.nil?
    dest_location = Locale.location(params[:destination]).first
    dest_location = Locale.create!(:name => params[:destination]) if dest_location.nil?

    @trip_segment = TripSegment.new(params[:trip_segment].merge({:locale_origin_id => org_location.id, :locale_destination_id => dest_location.id} ))
    if @trip_segment.save
      redirect_to trip_segments_path
    else
      render :new
    end
  end

  def limit_by_destination
    @trip_segments = TripSegment.destination(params[:destination])  # Rails3 use of scope method
  end

  def order_by_distance
    @destination = params[:destination]
    @trip_segments = TripSegment.order_by_miles_to_destination(@destination)  # Rails3 use of scope method that reuses another scope.
  end

  def destroy
    @destroyed_trip_segment = params[:id]
    TripSegment.find(@destroyed_trip_segment).delete
  end

  def search
    @locale = params[:locale]
    @trip_segments = TripSegment.search(@locale )

    render "searched_segments"
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
  end

  def index_all
    # want to implement a simple use of include or join.
    @trips = Trip.super_chained_join_scope
    @eager_trips = Trip.super_chained_include_scope
  end

  def new
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def create
    @trip = Trip.new(params[:trip])
    if @trip.save
     redirect_to trip_path(@trip)
    else
     render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/trip_segment_helper.rb
module TripSegmentHelper

  def longest_segment_length
    seg = TripSegment.longest_segment
    return seg.distance_in_miles unless seg.nil?
    return "No segments exisit"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traveler</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locales/index.html.erb
<%= static_map_of_addresses([Locale.new(:name => "My House", :lat => 42.04, :lng => -87.79), Locale.new(:name => "That House", :lat => 22.04, :lng => -87.79)]) %>

<br>
<%= link_to "All Trips", trips_path %>

app/views/locales/show.html.erb
<%= static_map_of_addresses([@locale]) %>

<br>
<%= link_to "All Trips", trips_path %>

app/views/locales/show_locales.html.erb
<%= static_map_of_addresses([@locales]) %>

<br>
<%= link_to "All Trips", trips_path %>

app/views/trip_segments/_back.html.erb
<div id="trip_segment_back" style="display:none">
  <br>
  <br>
  <%= link_to "Back to All Trips", trip_segments_path %>
</div>

app/views/trip_segments/_trip_segment.html.erb
<div id="<%= "trip_segment_"+trip_segment.id.to_s %>">
  <div>
  <%= link_to trip_segment.name, trip_segment_path(trip_segment.id) %> <%= link_to "map", locales_seg_path(trip_segment.locale_origin.name,trip_segment.locale_destination.name) %> [<%= link_to "delete", trip_segment_path(trip_segment.id), :remote => true, :method => "delete" %>]:
  </div>
  <div>
  <%= trip_segment.locale_origin.name %>==> <%= link_to trip_segment.locale_destination.name, destination_path(trip_segment.locale_destination_id), :remote => true %> <%= link_to "map", locale_path(trip_segment.locale_destination_id) %>
  </div>
  <div>
  <%= trip_segment.distance_in_miles %> miles
  </div>
  <div>
    Started: <%= trip_segment.start_date.to_date.to_formatted_s(:long) unless trip_segment.start_date.nil? %><br>
    Finished: <%= trip_segment.end_date.to_date.to_formatted_s(:long) unless trip_segment.end_date.nil? %><br>
  </div>
  <br>
</div>

<% # @hong_kong_trips.each { |hkg| p hkg.name } unless @hong_kong_trips.nil? %>

app/views/trip_segments/destroy.js.erb
$("trip_segment_"+<%= @destroyed_trip_segment %>).remove();

app/views/trip_segments/edit.html.erb
<p>Edit Trip Segment:</p>

<div>
  <%= form_for :trip_segment, @trip_segment, :url => { :action => "update"}, :html => {:method => :put}  do |f| %>

    <%= label_tag 'name' %>
    <%= f.text_field :name %><br>
    <%= label_tag 'origin' %>
    <%= f.text_field :origin %><br>
    <%= label_tag 'destination' %>
    <%= f.text_field :destination %><br>
    <%= label_tag 'miles traveled' %>
    <%= f.text_field :distance_in_miles %>

    <br>
    <%= submit_tag "Update" %>
  <% end %>
</div>
<%= render :partial => "back" %>

<script>
  $("trip_segment_back").show();
</script>

app/views/trip_segments/index.html.erb
<p>TRIP SEGMENTS:</p>
<div id="trip_segments">
  <!-- Rails3 querying -->
  <% TripSegment.find_each(:batch_size => 2) do |segment| %>
    <%= render :partial => "trip_segment", :object => segment %>
  <% end%>
</div>

<p>
<%= "No Trip Segments yet: get going!" unless TripSegment.exists? %>

<div>
  <%= form_tag('/trip_segments/search', options = {:method => "get"} ) do %>
    <%= label_tag 'name' %>
    <%= text_field_tag :locale %>
    <%= submit_tag "Search" %>
  <% end %>
</div>
<br><br>

<div id="trip_segment_nav">
  <%= link_to "Order by origin", order_by_origin_trip_segments_path, :remote => true %>

  <br>
  <br>
  <%= link_to "Add a Trip Segment", new_trip_segment_path %>
</div>
<div id="trip_segment_dest_order" style="display:none">
</div>
<%= render :partial => "back" %>

<br>
<%= link_to "All Trips", trips_path %>



<!--
  NOTE: Output from the "batch_size" param on the find_each:
  TripSegment Load (0.2ms)  SELECT "trip_segments".* FROM "trip_segments" WHERE ("trip_segments"."id" >= 0) ORDER BY trip_segments.id ASC LIMIT 2
Rendered trip_segments/_trip_segment.html.erb (9.3ms)
Rendered trip_segments/_trip_segment.html.erb (1.2ms)
  TripSegment Load (0.3ms)  SELECT "trip_segments".* FROM "trip_segments" WHERE ("trip_segments"."id" > 11) ORDER BY trip_segments.id ASC LIMIT 2
Rendered trip_segments/_trip_segment.html.erb (1.3ms)
Rendered trip_segments/_trip_segment.html.erb (1.5ms)
  TripSegment Load (0.3ms)  SELECT "trip_segments".* FROM "trip_segments" WHERE ("trip_segments"."id" > 13) ORDER BY trip_segments.id ASC LIMIT 2
Rendered trip_segments/_trip_segment.html.erb (1.2ms)
Rendered trip_segments/_trip_segment.html.erb (11.3ms)
  TripSegment Load (0.3ms)  SELECT "trip_segments".* FROM "trip_segments" WHERE ("trip_segments"."id" > 15) ORDER BY trip_segments.id ASC LIMIT 2
-->

app/views/trip_segments/index_by_trip.html.erb
<p>TRIP SEGMENTS for <%= @trip.name %>:</p>
<div id="trip_segments">
  <% @trip.trip_segments.each do |segment| %>
    <%= render :partial => "trip_segment", :object => segment %>
  <% end%>
</div>

<p>
<%= "No Trip Segments yet: get going!" unless @trip.trip_segments.exists? %>

<div id="trip_segment_nav">
  <br>
  <%= link_to "Add a Trip Segment", new_trip_segment_path %>
</div>
<div id="trip_segment_dest_order" style="display:none">
</div>
<%= render :partial => "back" %>

<br>
<%= link_to "All Trips", trips_path %>

app/views/trip_segments/index_ordered_by_origin.js.erb
$("trip_segments").update("<%= escape_javascript(render(@trip_segments))%>");

app/views/trip_segments/limit_by_destination.js.erb
$("trip_segments").update("<%= escape_javascript(render(@trip_segments))%>");
$("trip_segment_nav").hide()
$("trip_segment_back").show()

$("trip_segment_dest_order").update("<%= escape_javascript(link_to 'Order by distance',order_by_destination_distance_path(@destination), :remote => true)%>").show();

app/views/trip_segments/new.html.erb
<% # do it here for possible caching? %>
<% @trip_segment = TripSegment.new %>

<p>Add a Trip Segment:</p>
<div>
  <%= form_for :trip_segment, @trip_segment, :url => { :action => "create" } do |f| %>

    <%= select("trip_segment", "trip_id", Trip.all.collect {|t| [ t.name, t.id ] }) %><br>

    <%= label_tag 'name' %>
    <%= f.text_field :name, :label => 'name' %><br>
    <%= label_tag 'origin' %>
    <%= text_field_tag :origin %><br>
    <%= label_tag 'destination' %>
    <%= text_field_tag :destination %><br>
    <%= label_tag 'miles traveled' %>
    <%= f.text_field :distance_in_miles %>  <=== in the future should be autogenerated<br>

    Segment started: <%= date_select :trip_segment, :start_date %><br>
    Segment finished: <%= date_select :trip_segment, :end_date %>

    <br>
    <%= submit_tag "Create" %>
  <% end %>
</div>
<%= render :partial => "back" %>

<script>
  $("trip_segment_back").show();
</script>

app/views/trip_segments/order_by_distance.js.erb
$("trip_segments").update("<%= escape_javascript(render(@trip_segments))%>");
$("trip_segment_nav").hide()
$("trip_segment_back").show()

app/views/trip_segments/searched_segments.html.erb
<p>TRIP SEGMENTS for <%= @locale %>:</p>
<div id="trip_segments">
  <% @trip_segments.each do |segment| %>
    <%= render :partial => "trip_segment", :object => segment %>
  <% end%>
</div>

<p>
<%= "No Trip Segments yet: get going!" unless @trip_segments.exists? %>

<div id="trip_segment_nav">
  <br>
  <%= link_to "Add a Trip Segment", new_trip_segment_path %>
</div>
<div id="trip_segment_dest_order" style="display:none">
</div>
<%= render :partial => "back" %>

<br>
<%= link_to "All Trips", trips_path %>

app/views/trip_segments/show.html.erb
<p>Trip Segment Name: <%= @trip_segment.name %></p>

<div>
<%= link_to "Route: #{@trip_segment.locale_origin.name} ==> #{@trip_segment.locale_destination.name}", edit_trip_segment_path(@trip_segment) %>
<br>
Miles Traveled: <%= @trip_segment.distance_in_miles %>
</div>


<%= render :partial => "back" %>


<script>
  $("trip_segment_back").show();
</script>

app/views/trips/index.html.erb
<p>ALL TRIPS:</p>
<div id="trips">
  <% Trip.find_each(:batch_size => 2) do |trip| %>
    <div id="<%= "trip_"+trip.id.to_s %>">
      <%= link_to trip.name, trip_path(trip.id) %> ====> <%= link_to "trip segments", all_segments_for_trip_path(trip.id) %>
    </div>
  <% end%>
</div>

<div>
<br>
<%= link_to "Add a Trip", new_trip_path %>
</div>

<div>
<br>
<%= link_to "Trip Segments", trip_segments_path %>
</div>

<div>
<br>
<%= link_to "Super join scope", index_all_trips_path %>
</div>

app/views/trips/index_all.html.erb
<p>ALL TRIPS :: SEGMENT:</p>

<p>joined</p>
<% @trips.each do |trip| %>
  <%= trip.tname%> :: <%= trip.sname%><br>
<% end %>

<p>included</p>
<% @eager_trips.each do |trip| %>
  <%= trip.name %><br>
<% end %>

<br>
<br>
<%= link_to "Back to All Trips", trips_path %>

<div>
<br>
<%= link_to "Trip Segments", trip_segments_path %>
</div>

app/views/trips/new.html.erb
<% @trip = Trip.new %>

<p>Add a Trip:</p>
<div>
  <%= form_for :trip, @trip, :url => { :action => "create" } do |f| %>
    <%= label_tag 'name' %>
    <%= f.text_field :name %>
    <br>
    <%= submit_tag "Create" %>
  <% end %>
</div>

app/views/trips/show.html.erb
<p>TripName: <%= @trip.name %> <%= link_to "map", all_locales_trip_path(@trip.id) if @trip.trip_segments.exists? %></p>

<% if @trip.trip_segments.exists? %>
  <div>
  Total miles: <%= @trip.total_miles %> via <%= pluralize(@trip.trip_segments.count, 'segment') %><br>
  Longest segment: <%= @trip.longest_segment_of_trip.name %> of <%= @trip.longest_segment_of_trip.distance_in_miles %> miles<br>
  <br>
<% end %>
Longest segment (all trips): <%= longest_segment_length %>


</div>

<br>
<br>
<%= link_to "Back to All Trips", trips_path %>